spring.application.name=chatterbox
server.port=8080

# postgres database config
spring.datasource.url=jdbc:postgresql://localhost:5432/chatterbox
spring.datasource.username=postgres
spring.datasource.password=nguyenkhang

# mongodb database config
spring.data.mongodb.uri=mongodb://localhost:27017/chatterbox
spring.data.mongodb.database=chatterbox

#hibernate config
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

# redis config
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.database=0
spring.data.redis.timeout=60000

# mail server config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=heinsbergnguyen@gmail.com
spring.mail.password=rfwp lsqh gdxn wbsx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# jwt config
jwt.secret=3f9a2b7c8d1e4f6a9b0c3e5d7f1a2b4c6d8e0f9a1b2c3d4e5f6a7b8c9d0e1f2
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000